### ISSUE TITLE
How to send notifications using these scripts?

### ISSUE THREAD

**Issue by KshitijDroid** [sourc7/FCMStream#1]
Documentation is not clear.

**Comment by sourc7** [comment]
I'm sorry about the documentation, but I'll update that later.

FCMStream purpose is to be FCM app server to receive message from client app.

You can modify the service.php at handling the incoming message (including send callback to client app), at default service.php just output (echo) the message to the terminal.

Did you want to callback the incoming message?

**Comment by KshitijDroid** [comment]
Yes sir! That would be great... :D
